/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiAdminProvidersRouteImport } from './routes/api/admin/providers'
import { Route as ApiAuthBootstrapRouteImport } from './routes/api/auth/bootstrap'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProvidersRoute = ApiAdminProvidersRouteImport.update({
  id: '/api/admin/providers',
  path: '/api/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthBootstrapRoute = ApiAuthBootstrapRouteImport.update({
  id: '/api/auth/bootstrap',
  path: '/api/auth/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/export': typeof ApiExportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/admin/providers': typeof ApiAdminProvidersRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/export': typeof ApiExportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/admin/providers': typeof ApiAdminProvidersRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/export': typeof ApiExportRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/admin/providers': typeof ApiAdminProvidersRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/conversations'
    | '/api/export'
    | '/api/uploads'
    | '/api/admin/providers'
    | '/api/auth/bootstrap'
    | '/api/auth/login'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/conversations'
    | '/api/export'
    | '/api/uploads'
    | '/api/admin/providers'
    | '/api/auth/bootstrap'
    | '/api/auth/login'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/conversations'
    | '/api/export'
    | '/api/uploads'
    | '/api/admin/providers'
    | '/api/auth/bootstrap'
    | '/api/auth/login'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAdminProvidersRoute: typeof ApiAdminProvidersRoute
  ApiAuthBootstrapRoute: typeof ApiAuthBootstrapRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/providers': {
      id: '/api/admin/providers'
      path: '/api/admin/providers'
      fullPath: '/api/admin/providers'
      preLoaderRoute: typeof ApiAdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/bootstrap': {
      id: '/api/auth/bootstrap'
      path: '/api/auth/bootstrap'
      fullPath: '/api/auth/bootstrap'
      preLoaderRoute: typeof ApiAuthBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRoute,
  ApiExportRoute: ApiExportRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAdminProvidersRoute: ApiAdminProvidersRoute,
  ApiAuthBootstrapRoute: ApiAuthBootstrapRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
